---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata: "@ignore@"
  spec: "@ignore@"
- apiVersion: apps/v1
  kind: Deployment
  spec:
    replicas: 1
    revisionHistoryLimit: 8